services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - msnetwork
    volumes:
      - ./postgresql:/var/lib/postgresql/data

networks:
  msnetwork:
    driver: bridge